# Generated by Django 5.0.3 on 2025-03-16 08:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Storedata', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Account',
        ),
    ]
